/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ParagraphSwipePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/lib/coords.ts
function isValidBounds(rect) {
  return rect !== null && Number.isFinite(rect.top) && Number.isFinite(rect.bottom);
}
function findLineIndexAtY(lineCount, y, rectAt) {
  if (!Number.isInteger(lineCount) || lineCount <= 0) {
    return null;
  }
  let low = 0;
  let high = lineCount - 1;
  let candidate = null;
  while (low <= high) {
    const mid = Math.floor((low + high) / 2);
    const rect = rectAt(mid);
    if (!isValidBounds(rect)) {
      return null;
    }
    if (y < rect.top) {
      high = mid - 1;
    } else if (y > rect.bottom) {
      candidate = mid;
      low = mid + 1;
    } else {
      return mid;
    }
  }
  return candidate;
}
function findVisibleLineIndexAtY(firstVisible, lastVisible, y, rectAt) {
  if (!Number.isInteger(firstVisible) || !Number.isInteger(lastVisible) || firstVisible < 0 || lastVisible < firstVisible) {
    return null;
  }
  for (let line = firstVisible; line <= lastVisible; line += 1) {
    const rect = rectAt(line);
    if (isValidBounds(rect) && y >= rect.top && y <= rect.bottom) {
      return line;
    }
  }
  return null;
}

// src/lib/runtime-probe.ts
function safely(probe) {
  try {
    return probe();
  } catch (error) {
    console.warn("Paragraph Swipe: a runtime probe failed", error);
    return null;
  }
}
function readProperty(host, key) {
  return host[key];
}
function readFunction(host, key) {
  const value = readProperty(host, key);
  if (typeof value !== "function") {
    return null;
  }
  return value;
}
function readNumber(host, key) {
  const value = readProperty(host, key);
  const raw = typeof value === "function" ? safely(() => value.call(host)) : value;
  return typeof raw === "number" && Number.isFinite(raw) ? raw : null;
}
function readElement(host, key) {
  const value = readProperty(host, key);
  if (typeof value !== "object" || value === null) {
    return null;
  }
  const record = value;
  if (typeof record["getBoundingClientRect"] !== "function") {
    return null;
  }
  return value;
}

// src/editor-position.ts
function asEditorPosition(value) {
  if (typeof value !== "object" || value === null) {
    return null;
  }
  const record = value;
  const line = record["line"];
  const ch = record["ch"];
  if (typeof line !== "number" || !Number.isInteger(line) || line < 0) {
    return null;
  }
  if (typeof ch !== "number" || !Number.isFinite(ch) || ch < 0) {
    return null;
  }
  return { line, ch: Math.floor(ch) };
}
function asVerticalBounds(value) {
  if (typeof value !== "object" || value === null) {
    return null;
  }
  const record = value;
  const top = record["top"];
  const bottom = record["bottom"];
  if (typeof top !== "number" || typeof bottom !== "number" || !Number.isFinite(top) || !Number.isFinite(bottom)) {
    return null;
  }
  return { top, bottom };
}
function posFromEditorWrapper(editor, point) {
  const posAtCoords = readFunction(editor, "posAtCoords");
  if (posAtCoords === null) {
    return null;
  }
  return safely(() => asEditorPosition(posAtCoords.call(editor, point)));
}
function posFromCodeMirrorView(editor, point) {
  const cmView = readProperty(editor, "cm");
  if (typeof cmView !== "object" || cmView === null) {
    return null;
  }
  const posAtCoords = readFunction(cmView, "posAtCoords");
  if (posAtCoords === null) {
    return null;
  }
  const result = safely(() => posAtCoords.call(cmView, point));
  if (result === null) {
    return null;
  }
  if (typeof result === "number") {
    if (!Number.isFinite(result) || result < 0) {
      return null;
    }
    return safely(() => editor.offsetToPos(result));
  }
  return asEditorPosition(result);
}
function posFromLineScan(editor, y) {
  const coordsAtPos = readFunction(editor, "coordsAtPos");
  if (coordsAtPos === null) {
    return null;
  }
  const rectAt = (line2) => safely(() => asVerticalBounds(coordsAtPos.call(editor, { line: line2, ch: 0 })));
  const firstVisible = readNumber(editor, "getFirstVisibleLine");
  const lastVisible = readNumber(editor, "getLastVisibleLine");
  const line = firstVisible !== null && lastVisible !== null ? findVisibleLineIndexAtY(firstVisible, lastVisible, y, rectAt) : findLineIndexAtY(editor.lineCount(), y, rectAt);
  return line === null ? null : { line, ch: 0 };
}
function posAtClientPoint(editor, x, y) {
  if (!Number.isFinite(x) || !Number.isFinite(y)) {
    return null;
  }
  const point = { x, y };
  const fromWrapper = posFromEditorWrapper(editor, point);
  if (fromWrapper !== null) {
    return { position: fromWrapper, strategy: "editor.posAtCoords" };
  }
  const fromCodeMirror = posFromCodeMirrorView(editor, point);
  if (fromCodeMirror !== null) {
    return { position: fromCodeMirror, strategy: "editor.cm.posAtCoords" };
  }
  const fromScan = posFromLineScan(editor, y);
  if (fromScan !== null) {
    return { position: fromScan, strategy: "coordsAtPos line scan" };
  }
  return null;
}
function describePositionStrategies(editor) {
  const wrapperPos = readFunction(editor, "posAtCoords") !== null;
  const cm = readProperty(editor, "cm");
  const cmPresent = typeof cm === "object" && cm !== null;
  const cmPos = cmPresent ? readFunction(cm, "posAtCoords") !== null : false;
  const coordsAtPos = readFunction(editor, "coordsAtPos") !== null;
  const firstVisible = readNumber(editor, "getFirstVisibleLine");
  const lastVisible = readNumber(editor, "getLastVisibleLine");
  return [
    `editor.posAtCoords: ${wrapperPos ? "yes" : "no"}`,
    `editor.cm: ${cmPresent ? "yes" : "no"}`,
    `cm.posAtCoords: ${cmPos ? "yes" : "no"}`,
    `editor.coordsAtPos: ${coordsAtPos ? "yes" : "no"}`,
    `visible lines: ${firstVisible}/${lastVisible}`
  ].join(", ");
}
function isEditorEditable(editor) {
  const getEditable = readFunction(editor, "getEditable");
  return getEditable === null ? true : Boolean(safely(() => getEditable.call(editor)));
}

// src/lib/gesture.ts
var MIN_VERTICAL_TOLERANCE_PX = 24;
var DECISION_DISTANCE_PX = 10;
var DRAWER_EDGE_ZONE_PX = 32;
function verticalTolerancePx(swipeThresholdPx) {
  return Math.max(MIN_VERTICAL_TOLERANCE_PX, Math.round(swipeThresholdPx / 2));
}
function isCRAZYIntent(deltaX) {
  return deltaX >= 1;
}
function isDrawerZoneStart(startX) {
  return Number.isFinite(startX) && startX <= DRAWER_EDGE_ZONE_PX;
}
function decisionDistancePx(startX) {
  return isDrawerZoneStart(startX) ? 1 : DECISION_DISTANCE_PX;
}
function swipeProgress(deltaX, swipeThresholdPx) {
  if (!Number.isFinite(deltaX) || deltaX <= 0) {
    return 0;
  }
  const threshold = swipeThresholdPx > 0 ? swipeThresholdPx : 1;
  return Math.pow(Math.min(1, deltaX / threshold), 0.6);
}
function isRightwardSwipe(deltaX, deltaY, swipeThresholdPx) {
  if (deltaX < swipeThresholdPx) {
    return false;
  }
  return Math.abs(deltaY) <= verticalTolerancePx(swipeThresholdPx);
}
function decideGesture(deltaX, deltaY, decisionDistancePxValue = DECISION_DISTANCE_PX) {
  const absoluteX = Math.abs(deltaX);
  const absoluteY = Math.abs(deltaY);
  if (Math.max(absoluteX, absoluteY) < decisionDistancePxValue) {
    return "undecided";
  }
  if (absoluteY > absoluteX) {
    return "vertical";
  }
  return deltaX > 0 ? "rightward" : "leftward";
}
function touchById(touches, identifier) {
  for (let index = 0; index < touches.length; index += 1) {
    const touch = touches[index];
    if (touch.identifier === identifier) {
      return touch;
    }
  }
  return null;
}

// src/lib/paragraph.ts
function isBlankLine(line) {
  return line.trim().length === 0;
}
function splitLines(text) {
  return text.split("\n");
}
function joinLines(lines) {
  return lines.join("\n");
}
function normalizeLineEndings(text) {
  return text.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
}
function getParagraphRange(lines, lineIndex) {
  if (!Number.isInteger(lineIndex) || lineIndex < 0 || lineIndex >= lines.length) {
    return null;
  }
  if (isBlankLine(lines[lineIndex])) {
    return null;
  }
  let start = lineIndex;
  while (start > 0 && !isBlankLine(lines[start - 1])) {
    start -= 1;
  }
  let end = lineIndex + 1;
  while (end < lines.length && !isBlankLine(lines[end])) {
    end += 1;
  }
  return { start, end };
}
function extractParagraphLines(lines, range) {
  return lines.slice(range.start, range.end);
}
function getDeletionRange(lines, range) {
  const { start, end } = range;
  let deletionStart = start;
  let deletionEnd = end;
  if (start === 0) {
    if (end < lines.length && isBlankLine(lines[end])) {
      deletionEnd = end + 1;
    }
  } else if (end === lines.length) {
    if (isBlankLine(lines[start - 1])) {
      deletionStart = start - 1;
    }
  } else if (isBlankLine(lines[end])) {
    deletionEnd = end + 1;
  } else if (isBlankLine(lines[start - 1])) {
    deletionStart = start - 1;
  }
  return { start: deletionStart, end: deletionEnd };
}
function toCharRange(lines, deletion) {
  if (lines.length === 0) {
    return { from: { line: 0, ch: 0 }, to: { line: 0, ch: 0 } };
  }
  const lastIndex = lines.length - 1;
  if (deletion.start > 0) {
    return {
      from: { line: deletion.start - 1, ch: lines[deletion.start - 1].length },
      to: { line: deletion.end - 1, ch: lines[deletion.end - 1].length }
    };
  }
  if (deletion.end <= lastIndex) {
    return { from: { line: 0, ch: 0 }, to: { line: deletion.end, ch: 0 } };
  }
  return { from: { line: 0, ch: 0 }, to: { line: lastIndex, ch: lines[lastIndex].length } };
}
function appendParagraphToText(target, paragraph) {
  const base = splitLines(target);
  while (base.length > 0 && isBlankLine(base[base.length - 1])) {
    base.pop();
  }
  if (paragraph.trim().length === 0) {
    return joinLines(base);
  }
  if (base.length === 0) {
    return paragraph;
  }
  const appended = joinLines(base.concat([""], splitLines(paragraph)));
  return target.endsWith("\n") ? `${appended}
` : appended;
}

// src/note-picker-modal.ts
var import_obsidian = require("obsidian");

// src/lib/notes-search.ts
function tokenizeQuery(query) {
  return query.toLowerCase().split(/\s+/).filter((token) => token.length > 0);
}
function parentFolderPath(path) {
  const index = path.lastIndexOf("/");
  if (index <= 0) {
    return "/";
  }
  return path.slice(0, index);
}
function matchesAllTokens(path, tokens) {
  return tokens.every((token) => path.includes(token));
}
function filterAndSortNotes(candidates, query) {
  const tokens = tokenizeQuery(query);
  const matching = tokens.length === 0 ? candidates.slice() : candidates.filter((candidate) => matchesAllTokens(candidate.path.toLowerCase(), tokens));
  return matching.sort((a, b) => b.mtime - a.mtime || a.path.localeCompare(b.path));
}

// src/note-picker-modal.ts
var NotePickerModal = class extends import_obsidian.SuggestModal {
  constructor(app, sourcePath, onPick) {
    super(app);
    this.onPick = onPick;
    const files = app.vault.getMarkdownFiles().filter((file) => file.path !== sourcePath);
    this.candidates = files;
    const filesByPath = /* @__PURE__ */ new Map();
    for (const file of files) {
      filesByPath.set(file.path, file);
    }
    this.filesByPath = filesByPath;
    this.modalEl.addClass("paragraph-swipe-modal");
    this.emptyStateText = "No notes found.";
    this.setInstructions([
      { command: "\u2191\u2193", purpose: "navigate" },
      { command: "\u21B5", purpose: "move paragraph" },
      { command: "esc", purpose: "dismiss" }
    ]);
  }
  getSuggestions(query) {
    const notes = this.candidates.map((file) => ({
      path: file.path,
      mtime: file.stat.mtime
    }));
    const matches = filterAndSortNotes(notes, query);
    const suggestions = [];
    for (const match of matches) {
      const file = this.filesByPath.get(match.path);
      if (file !== void 0) {
        suggestions.push(file);
      }
    }
    return suggestions;
  }
  renderSuggestion(file, el) {
    el.createDiv({ cls: "paragraph-swipe-suggestion-title", text: file.basename });
    const folder = parentFolderPath(file.path);
    const folderLabel = folder === "/" ? "" : `${folder} \xB7 `;
    el.createDiv({
      cls: "paragraph-swipe-suggestion-details",
      text: `${folderLabel}${new Date(file.stat.mtime).toLocaleString()}`
    });
  }
  onChooseSuggestion(file, _evt) {
    this.onPick(file);
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");
var DEFAULT_SETTINGS = {
  swipeThresholdPx: 100,
  debugMode: false
};
var MIN_SWIPE_THRESHOLD_PX = 20;
var MAX_SWIPE_THRESHOLD_PX = 600;
function clampSwipeThreshold(value) {
  if (!Number.isFinite(value)) {
    return DEFAULT_SETTINGS.swipeThresholdPx;
  }
  return Math.min(MAX_SWIPE_THRESHOLD_PX, Math.max(MIN_SWIPE_THRESHOLD_PX, Math.round(value)));
}
var ParagraphSwipeSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Swipe threshold").setDesc(
      "Minimum horizontal finger travel in pixels that opens the note picker when swiping right over a paragraph."
    ).addText((text) => {
      text.setPlaceholder(String(DEFAULT_SETTINGS.swipeThresholdPx));
      text.setValue(String(this.plugin.settings.swipeThresholdPx));
      text.inputEl.type = "number";
      text.inputEl.min = String(MIN_SWIPE_THRESHOLD_PX);
      text.inputEl.max = String(MAX_SWIPE_THRESHOLD_PX);
      text.inputEl.step = "10";
      text.onChange((value) => {
        if (value.trim().length === 0) {
          return;
        }
        const parsed = Number(value);
        if (!Number.isFinite(parsed)) {
          return;
        }
        this.plugin.settings.swipeThresholdPx = clampSwipeThreshold(parsed);
        void this.plugin.saveSettings();
      });
      return text;
    });
    new import_obsidian2.Setting(containerEl).setName("Debug notices").setDesc("Show a toast at every step of the swipe pipeline to diagnose gesture problems.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.debugMode);
      toggle.onChange((value) => {
        this.plugin.settings.debugMode = value;
        void this.plugin.saveSettings();
      });
      return toggle;
    });
  }
};

// src/swipe-cut.ts
var ACTIVE_CLASS = "paragraph-swipe-active";
var CARRIER_CLASS = "paragraph-swipe-carrier";
var LINE_CLASS = "paragraph-swipe-line";
var SLOT_CLASS = "paragraph-swipe-slot";
var PLATE_CLASS = "paragraph-swipe-plate";
var PLATE_OUT_CLASS = "paragraph-swipe-plate--out";
var PLATE_DETACHED_CLASS = "paragraph-swipe-plate--detached";
var SHIFT_PROPERTY = "--paragraph-swipe-shift";
var PROGRESS_PROPERTY = "--paragraph-swipe-progress";
var RELEASE_MS = 180;
var DETACH_MS = 220;
var PROBE_INSET_PX = 2;
function clampProgress(value) {
  if (!Number.isFinite(value)) {
    return 0;
  }
  return Math.min(1, Math.max(0, value));
}
function editorRoot(view) {
  const cm = readProperty(view.editor, "cm");
  if (typeof cm === "object" && cm !== null) {
    const dom = readElement(cm, "dom");
    if (dom !== null) {
      return dom;
    }
  }
  const content = view.contentEl.querySelector(".cm-content");
  return content instanceof HTMLElement ? content : view.contentEl;
}
function renderedLines(view) {
  const container = view.contentEl.querySelector(".cm-content");
  if (!(container instanceof HTMLElement)) {
    return null;
  }
  const lines = Array.from(container.querySelectorAll(".cm-line"));
  return lines.length > 0 ? lines : null;
}
function firstRenderedLine(view, lines) {
  var _a, _b;
  const fromViewport = readNumber(view.editor, "getFirstVisibleLine");
  if (fromViewport !== null) {
    return fromViewport;
  }
  const first = lines[0];
  if (first === void 0) {
    return null;
  }
  const rect = first.getBoundingClientRect();
  if (!Number.isFinite(rect.top) || !Number.isFinite(rect.bottom) || rect.bottom <= rect.top) {
    return null;
  }
  const y = rect.top < 0 ? rect.bottom - PROBE_INSET_PX : rect.top + PROBE_INSET_PX;
  return (_b = (_a = posAtClientPoint(view.editor, rect.left + PROBE_INSET_PX, y)) == null ? void 0 : _a.position.line) != null ? _b : null;
}
function paragraphLines(view, range) {
  const lines = renderedLines(view);
  if (lines === null) {
    return "no-lines";
  }
  const firstRendered = firstRenderedLine(view, lines);
  if (firstRendered === null) {
    return "no-position";
  }
  const from = range.start - firstRendered;
  if (from < 0 || from >= lines.length) {
    return "not-rendered";
  }
  return lines.slice(from, Math.min(from + (range.end - range.start), lines.length));
}
function unionRect(elements) {
  let top = Number.POSITIVE_INFINITY;
  let bottom = Number.NEGATIVE_INFINITY;
  let left = Number.POSITIVE_INFINITY;
  let right = Number.NEGATIVE_INFINITY;
  for (const element of elements) {
    const rect = element.getBoundingClientRect();
    if (!Number.isFinite(rect.top) || !Number.isFinite(rect.bottom)) {
      return null;
    }
    top = Math.min(top, rect.top);
    bottom = Math.max(bottom, rect.bottom);
    left = Math.min(left, rect.left);
    right = Math.max(right, rect.right);
  }
  const visibleTop = Math.max(top, 0);
  const visibleBottom = Math.min(bottom, window.innerHeight);
  if (visibleBottom <= visibleTop || right <= left) {
    return null;
  }
  return { top: visibleTop, bottom: visibleBottom, left, right };
}
function appendOverlay(cls, rect) {
  const element = document.createElement("div");
  element.className = cls;
  element.style.top = `${Math.round(rect.top)}px`;
  element.style.left = `${Math.round(rect.left)}px`;
  element.style.width = `${Math.round(rect.right - rect.left)}px`;
  element.style.height = `${Math.round(rect.bottom - rect.top)}px`;
  document.body.appendChild(element);
  return element;
}
var SwipeCut = class _SwipeCut {
  constructor(lines, root, scroller, slot, plate) {
    this.lastProgress = -1;
    this.finished = false;
    this.lines = lines;
    this.root = root;
    this.scroller = scroller;
    this.slot = slot;
    this.plate = plate;
  }
  /**
   * Cuts `range` out of `view`. Returns the effect, or the reason there is
   * none — the caller logs it, because on a phone there is no other way to
   * see why the effect did not come up.
   */
  static attach(view, range) {
    const located = paragraphLines(view, range);
    if (typeof located === "string") {
      return { cut: null, reason: located };
    }
    const rect = unionRect(located);
    if (rect === null) {
      return { cut: null, reason: "no-box" };
    }
    const root = editorRoot(view);
    const scroller = view.contentEl.querySelector(".cm-scroller");
    scroller == null ? void 0 : scroller.classList.add(CARRIER_CLASS);
    const slot = appendOverlay(SLOT_CLASS, rect);
    const plate = appendOverlay(PLATE_CLASS, rect);
    for (const line of located) {
      line.classList.add(LINE_CLASS);
    }
    root.classList.add(ACTIVE_CLASS);
    return { cut: new _SwipeCut(located, root, scroller, slot, plate), reason: null };
  }
  /** Moves the block to follow the finger. Horizontal travel, in pixels. */
  setShift(deltaX) {
    if (this.finished) {
      return;
    }
    const shift = Number.isFinite(deltaX) ? `${deltaX.toFixed(1)}px` : "0px";
    this.root.style.setProperty(SHIFT_PROPERTY, shift);
    this.plate.style.setProperty(SHIFT_PROPERTY, shift);
  }
  /**
   * Scales the effect: 0 is the first pixel of the swipe, 1 the threshold —
   * the point at which the paragraph really moves.
   */
  setProgress(progress) {
    if (this.finished) {
      return;
    }
    const clamped = clampProgress(progress);
    if (Math.abs(clamped - this.lastProgress) < 0.01) {
      return;
    }
    this.lastProgress = clamped;
    const value = clamped.toFixed(3);
    this.root.style.setProperty(PROGRESS_PROPERTY, value);
    this.plate.style.setProperty(PROGRESS_PROPERTY, value);
  }
  /** The swipe was abandoned: the block slides back into its slot. */
  release() {
    if (this.finished) {
      return;
    }
    this.plate.classList.add(PLATE_OUT_CLASS);
    this.scheduleCleanup(RELEASE_MS);
  }
  /** The block was accepted: it flies off to the right and leaves. */
  detach() {
    if (this.finished) {
      return;
    }
    this.plate.classList.add(PLATE_DETACHED_CLASS);
    this.scheduleCleanup(DETACH_MS);
  }
  /** Removes the effect at once, for when the text is about to move. */
  drop() {
    if (this.finished) {
      return;
    }
    this.cleanup();
  }
  scheduleCleanup(delayMs) {
    this.finished = true;
    window.setTimeout(() => {
      this.cleanup();
    }, delayMs);
  }
  cleanup() {
    var _a;
    this.finished = true;
    for (const line of this.lines) {
      line.classList.remove(LINE_CLASS);
    }
    this.root.classList.remove(ACTIVE_CLASS);
    this.root.style.removeProperty(SHIFT_PROPERTY);
    this.root.style.removeProperty(PROGRESS_PROPERTY);
    (_a = this.scroller) == null ? void 0 : _a.classList.remove(CARRIER_CLASS);
    this.slot.remove();
    this.plate.remove();
  }
};

// src/main.ts
function describeElement(element) {
  const id = element.id === "" ? "" : `#${element.id}`;
  const classes = element.className === "" ? "" : `.${String(element.className).trim().split(/\s+/).join(".")}`;
  return `${element.tagName.toLowerCase()}${id}${classes}`.slice(0, 60);
}
var ParagraphSwipePlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    this.gesture = null;
    /** The paragraph being carried away by the swipe in progress, if any. */
    this.cut = null;
  }
  async onload() {
    await this.loadSettings();
    this.debugLog(`loaded (threshold ${this.settings.swipeThresholdPx} px)`);
    this.addSettingTab(new ParagraphSwipeSettingTab(this.app, this));
    this.registerDomEvent(
      window,
      "touchstart",
      (event) => {
        this.onTouchStart(event);
      },
      { capture: true, passive: true }
    );
    this.registerDomEvent(
      window,
      "touchmove",
      (event) => {
        this.onTouchMove(event);
      },
      { capture: true, passive: false }
    );
    this.registerDomEvent(
      window,
      "touchend",
      (event) => {
        this.onTouchEnd(event);
      },
      { capture: true, passive: true }
    );
    this.registerDomEvent(
      window,
      "touchcancel",
      (event) => {
        this.onTouchCancel(event);
      },
      { capture: true, passive: true }
    );
    this.registerDomEvent(
      window,
      "scroll",
      () => {
        this.dropCut();
      },
      { capture: true, passive: true }
    );
    this.registerDomEvent(
      window,
      "pointermove",
      (event) => {
        this.onPointerMove(event);
      },
      { capture: true, passive: true }
    );
  }
  onunload() {
    this.gesture = null;
    this.dropCut();
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async loadSettings() {
    const stored = await this.loadData();
    this.settings = { ...DEFAULT_SETTINGS };
    if (typeof stored !== "object" || stored === null) {
      return;
    }
    const record = stored;
    const threshold = record["swipeThresholdPx"];
    if (typeof threshold === "number" && Number.isFinite(threshold)) {
      this.settings.swipeThresholdPx = clampSwipeThreshold(threshold);
    }
    if (typeof record["debugMode"] === "boolean") {
      this.settings.debugMode = record["debugMode"];
    }
  }
  /** Logs to the console always; additionally toasts when debug mode is on. */
  debugLog(message) {
    console.log(`Paragraph Swipe: ${message}`);
    if (this.settings.debugMode) {
      new import_obsidian3.Notice(`Paragraph Swipe: ${message}`, 8e3);
    }
  }
  isEditableSourceView(view) {
    return view.getMode() === "source" && isEditorEditable(view.editor);
  }
  /**
   * Finds the editable source-mode MarkdownView that contains the touched
   * element. The active view is checked first; the loop over all markdown
   * leaves covers swipes in unfocused split panes.
   */
  findSourceMarkdownView(target) {
    const active = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    if (active !== null && this.isEditableSourceView(active) && active.contentEl.contains(target)) {
      return active;
    }
    for (const leaf of this.app.workspace.getLeavesOfType("markdown")) {
      const view = leaf.view;
      if (view instanceof import_obsidian3.MarkdownView && this.isEditableSourceView(view) && view.contentEl.contains(target)) {
        return view;
      }
    }
    return null;
  }
  onTouchStart(event) {
    const activeGesture = this.gesture;
    if (activeGesture !== null && activeGesture.claimed && event.touches.length > 1) {
      return;
    }
    this.gesture = null;
    this.dropCut();
    const touch = event.touches[0];
    if (event.touches.length !== 1 || touch === void 0) {
      this.debugLog(`touchstart ignored: ${event.touches.length} finger(s)`);
      return;
    }
    const target = event.target;
    if (!(target instanceof Element)) {
      this.debugLog("touchstart ignored: the target is not an element");
      return;
    }
    const selection = window.getSelection();
    if (selection !== null && !selection.isCollapsed) {
      this.debugLog("touchstart ignored: there is a text selection");
      return;
    }
    const view = this.findSourceMarkdownView(target);
    if (view === null) {
      this.debugLog(`touchstart ignored: no editable source view under ${describeElement(target)}`);
      return;
    }
    this.debugLog(`touchstart at (${Math.round(touch.clientX)}, ${Math.round(touch.clientY)}) on ${describeElement(target)}`);
    this.gesture = {
      touchId: touch.identifier,
      startX: touch.clientX,
      startY: touch.clientY,
      view,
      leftDrawerOpenAtStart: this.isLeftDrawerOpen(),
      claimed: false,
      released: false,
      consumed: false,
      claimedMoves: 0,
      lastDeltaX: 0,
      paragraph: null,
      effectBroken: false
    };
  }
  onTouchMove(event) {
    const gesture = this.gesture;
    if (gesture === null || gesture.released) {
      this.debugLog("touchmove ignored: no live gesture");
      return;
    }
    const touch = touchById(event.changedTouches, gesture.touchId);
    if (gesture.claimedMoves === 0) {
      const first = touch === null ? null : touchById(event.changedTouches, gesture.touchId);
      this.debugLog(
        first === null ? "first touchmove: the finger is not in changedTouches" : `first touchmove: dx ${Math.round(first.clientX - gesture.startX)} px, dy ${Math.round(first.clientY - gesture.startY)} px`
      );
    }
    if (touch === null) {
      return;
    }
    const threshold = this.settings.swipeThresholdPx;
    if (gesture.claimed) {
      this.swallowTouch(event);
      gesture.claimedMoves += 1;
      const deltaX2 = touch.clientX - gesture.startX;
      gesture.lastDeltaX = deltaX2;
      this.feedCut(gesture, deltaX2);
      if (!gesture.consumed && deltaX2 >= threshold) {
        gesture.consumed = true;
        this.openPickerSafely(gesture);
      }
      return;
    }
    if (event.touches.length !== 1) {
      gesture.released = true;
      this.dropCut();
      return;
    }
    const deltaX = touch.clientX - gesture.startX;
    const deltaY = touch.clientY - gesture.startY;
    const decision = decideGesture(deltaX, deltaY, decisionDistancePx(gesture.startX));
    this.feedCut(gesture, deltaX);
    if (decision === "undecided") {
      return;
    }
    if (decision !== "rightward") {
      gesture.released = true;
      this.dropCut();
      return;
    }
    gesture.claimed = true;
    this.swallowTouch(event);
    this.debugLog(`swipe claimed (dx ${Math.round(deltaX)} px, dy ${Math.round(deltaY)} px)`);
    this.debugLog(`claimed at dx ${Math.round(deltaX)} px`);
    if (deltaX >= threshold) {
      gesture.consumed = true;
      this.openPickerSafely(gesture);
    }
  }
  onTouchEnd(event) {
    const gesture = this.gesture;
    if (gesture === null) {
      return;
    }
    const touch = touchById(event.changedTouches, gesture.touchId);
    if (touch === null) {
      this.dropCut();
      return;
    }
    this.gesture = null;
    const deltaX = touch.clientX - gesture.startX;
    const deltaY = touch.clientY - gesture.startY;
    if (gesture.claimed) {
      this.swallowTouch(event);
      if (gesture.consumed) {
        this.dropCut();
      } else if (deltaX >= this.settings.swipeThresholdPx) {
        gesture.consumed = true;
        this.debugLog(
          `opening the picker from the end event (dx ${Math.round(deltaX)} px; ${gesture.claimedMoves} move event(s) received after the claim)`
        );
        this.openPickerSafely(gesture);
      } else {
        this.debugLog(
          `swipe ended below the threshold (dx ${Math.round(deltaX)} px, dy ${Math.round(deltaY)} px, threshold ${this.settings.swipeThresholdPx} px, ${gesture.claimedMoves} move event(s) received)`
        );
        this.releaseCut();
      }
      this.collapseLeftDrawerIfOpenedByGesture(gesture);
      return;
    }
    if (gesture.released || gesture.consumed) {
      this.releaseCut();
      return;
    }
    if (decideGesture(deltaX, deltaY) === "rightward" && isRightwardSwipe(deltaX, deltaY, this.settings.swipeThresholdPx)) {
      this.openPickerSafely(gesture);
    } else {
      this.releaseCut();
    }
  }
  onTouchCancel(event) {
    const gesture = this.gesture;
    this.gesture = null;
    this.dropCut();
    if (gesture !== null && gesture.claimed) {
      this.swallowTouch(event);
      if (!gesture.consumed) {
        this.debugLog(
          `the system cancelled the swipe after the claim (${gesture.claimedMoves} move event(s) received, last dx ${Math.round(gesture.lastDeltaX)} px)`
        );
      }
      this.collapseLeftDrawerIfOpenedByGesture(gesture);
    }
  }
  /**
   * Hides the remaining events of a claimed gesture from the app and from
   * CodeMirror, so the built-in swipe-to-open-sidebar gesture is not
   * triggered and no stray click is synthesized.
   */
  swallowTouch(event) {
    event.stopImmediatePropagation();
    event.preventDefault();
  }
  /** Calls triggerSwipe, converting any unexpected exception into a visible notice. */
  openPickerSafely(gesture) {
    this.detachCut();
    try {
      this.triggerSwipe(gesture);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.error("Paragraph Swipe: failed to open the picker", error);
      new import_obsidian3.Notice(`Paragraph Swipe: internal error \u2014 ${message}`);
    }
  }
  /**
   * Progress channel for the effect: a pointermove only ever moves the block
   * along, it never claims or swallows anything. Gestures only start from a
   * touchstart, so there is nothing to do without one.
   */
  onPointerMove(event) {
    const gesture = this.gesture;
    if (gesture === null || gesture.released || this.cut === null || !event.isPrimary) {
      return;
    }
    const deltaX = event.clientX - gesture.startX;
    gesture.lastDeltaX = deltaX;
    this.feedCut(gesture, deltaX);
  }
  /**
   * Starts the effect if it is not up yet and carries it to the finger. The
   * whole feedback is optional: an exception in it must not abort the
   * touchmove handler, or the gesture would never be claimed and the app's own
   * edge gestures would take over. One failure disables it for the rest of
   * the gesture instead of repeating it on every move.
   */
  feedCut(gesture, deltaX) {
    if (gesture.effectBroken || gesture.consumed) {
      return;
    }
    try {
      if (this.cut === null) {
        if (!isCRAZYIntent(deltaX)) {
          return;
        }
        this.startCut(gesture, deltaX);
      } else {
        this.updateCut(deltaX);
      }
    } catch (error) {
      gesture.effectBroken = true;
      this.dropCut();
      console.warn("Paragraph Swipe: the cut effect failed and was switched off for this gesture", error);
      this.debugLog("the cut effect failed; the swipe itself keeps working");
    }
  }
  /**
   * Cuts the paragraph under the finger out of its note and hands it to the
   * swipe. Everything is measured once, here: from now on the gesture
   * swallows its own touchmove events, so the editor cannot scroll and the
   * block cannot drift away from the finger.
   */
  startCut(gesture, deltaX) {
    this.dropCut();
    const lookup = this.lookupParagraph(gesture.view, gesture.startX, gesture.startY);
    if (lookup.kind === "blank") {
      this.debugLog(`the swipe started on a blank line (line ${lookup.line + 1}); nothing to cut out`);
      return;
    }
    if (lookup.kind === "unresolved") {
      this.debugLog(`cannot resolve the editor position under the finger; ${lookup.detail}`);
      return;
    }
    gesture.paragraph = lookup;
    const { cut, reason } = SwipeCut.attach(gesture.view, lookup.range);
    if (cut === null) {
      this.debugLog(
        `the paragraph on lines ${lookup.range.start + 1}\u2013${lookup.range.end} cannot be cut out (${reason})`
      );
      return;
    }
    this.cut = cut;
    cut.setShift(deltaX);
    cut.setProgress(swipeProgress(deltaX, this.settings.swipeThresholdPx));
    this.debugLog(
      `the block on lines ${lookup.range.start + 1}\u2013${lookup.range.end} was cut out (${lookup.strategy})`
    );
  }
  /** Carries the block to the finger's position. A no-op without one. */
  updateCut(deltaX) {
    if (this.cut === null) {
      return;
    }
    this.cut.setShift(deltaX);
    this.cut.setProgress(swipeProgress(deltaX, this.settings.swipeThresholdPx));
  }
  /** The swipe was abandoned: the block glides back into its slot. */
  releaseCut() {
    const cut = this.cut;
    this.cut = null;
    cut == null ? void 0 : cut.release();
  }
  /** The block was accepted: it flies off to the right and leaves. */
  detachCut() {
    const cut = this.cut;
    this.cut = null;
    cut == null ? void 0 : cut.detach();
  }
  /** Snaps the block back at once, for when the text is about to move. */
  dropCut() {
    const cut = this.cut;
    this.cut = null;
    cut == null ? void 0 : cut.drop();
  }
  /** Runtime probe: `leftSplit.collapsed` differs between typings releases. */
  isLeftDrawerOpen() {
    const workspace = this.app.workspace;
    if (typeof workspace !== "object" || workspace === null) {
      return false;
    }
    const leftSplit = workspace["leftSplit"];
    if (typeof leftSplit !== "object" || leftSplit === null) {
      return false;
    }
    return leftSplit["collapsed"] === false;
  }
  /**
   * Safety net: if the drawer gesture still managed to open the left sidebar
   * during a claimed swipe (its listener may be registered earlier than
   * ours), close it again — but only if the sidebar was closed when the
   * gesture started, so a drawer opened deliberately is never touched.
   */
  collapseLeftDrawerIfOpenedByGesture(gesture) {
    if (gesture.leftDrawerOpenAtStart || !this.isLeftDrawerOpen()) {
      return;
    }
    const workspace = this.app.workspace;
    if (typeof workspace !== "object" || workspace === null) {
      return;
    }
    const leftSplit = workspace["leftSplit"];
    if (typeof leftSplit !== "object" || leftSplit === null) {
      return;
    }
    const collapse = leftSplit["collapse"];
    if (typeof collapse === "function") {
      collapse.call(leftSplit);
    }
  }
  /**
   * Finds the paragraph under the given viewport coordinates. Silent on
   * purpose: the swipe must not spam the debug log, so only the picker
   * reports why there is nothing to move.
   */
  lookupParagraph(view, x, y) {
    const editor = view.editor;
    const resolved = posAtClientPoint(editor, x, y);
    if (resolved === null) {
      return { kind: "unresolved", detail: describePositionStrategies(editor) };
    }
    const range = getParagraphRange(splitLines(editor.getValue()), resolved.position.line);
    if (range === null) {
      return { kind: "blank", line: resolved.position.line, strategy: resolved.strategy };
    }
    return { kind: "paragraph", range, strategy: resolved.strategy };
  }
  /**
   * The paragraph this gesture is about: the one the cut effect resolved, or
   * a fresh lookup for the rare flick that never got far enough to start one.
   */
  paragraphOf(gesture) {
    if (gesture.paragraph === null) {
      return this.lookupParagraph(gesture.view, gesture.startX, gesture.startY);
    }
    return { kind: "paragraph", range: gesture.paragraph.range, strategy: gesture.paragraph.strategy };
  }
  /** Opens the note picker for the paragraph this gesture started on. */
  triggerSwipe(gesture) {
    const view = gesture.view;
    const { startX: x, startY: y } = gesture;
    const lookup = this.paragraphOf(gesture);
    if (lookup.kind === "unresolved") {
      this.debugLog(
        `cannot resolve the editor position at (${Math.round(x)}, ${Math.round(y)}); ${lookup.detail}`
      );
      return;
    }
    if (lookup.kind === "blank") {
      this.debugLog(
        `the swipe started on a blank line (line ${lookup.line + 1}, via ${lookup.strategy}) \u2014 nothing to move`
      );
      return;
    }
    const sourceFile = view.file;
    if (!sourceFile) {
      this.debugLog("the note is not backed by a file; nothing to move");
      return;
    }
    this.debugLog(
      `opening the picker for the paragraph on lines ${lookup.range.start + 1}\u2013${lookup.range.end} (via ${lookup.strategy})`
    );
    const startLine = lookup.range.start;
    const modal = new NotePickerModal(this.app, sourceFile.path, (targetFile) => {
      void this.moveParagraph(view, startLine, targetFile).catch((error) => {
        const message = error instanceof Error ? error.message : String(error);
        new import_obsidian3.Notice(`Paragraph Swipe: failed to move the paragraph \u2014 ${message}`);
      });
    });
    modal.open();
  }
  async moveParagraph(sourceView, lineIndex, targetFile) {
    const editor = sourceView.editor;
    const sourceFile = sourceView.file;
    if (!sourceFile || targetFile.path === sourceFile.path) {
      this.debugLog("move aborted: no source file or the target equals the source");
      return;
    }
    const linesBefore = splitLines(editor.getValue());
    const rangeBefore = getParagraphRange(linesBefore, lineIndex);
    if (rangeBefore === null) {
      this.debugLog("move aborted: the paragraph disappeared before the pick");
      return;
    }
    const paragraph = joinLines(extractParagraphLines(linesBefore, rangeBefore));
    try {
      await this.app.vault.process(
        targetFile,
        (data) => appendParagraphToText(normalizeLineEndings(data), paragraph)
      );
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      new import_obsidian3.Notice(`Paragraph Swipe: could not update "${targetFile.basename}" \u2014 ${message}`);
      return;
    }
    const linesAfter = splitLines(editor.getValue());
    const rangeAfter = getParagraphRange(linesAfter, lineIndex);
    if (rangeAfter === null) {
      this.debugLog("move aborted: the paragraph vanished from the source note");
      return;
    }
    if (joinLines(extractParagraphLines(linesAfter, rangeAfter)) !== paragraph) {
      this.debugLog("move aborted: the source paragraph changed while the picker was open");
      return;
    }
    const deletion = getDeletionRange(linesAfter, rangeAfter);
    const charRange = toCharRange(linesAfter, deletion);
    editor.replaceRange("", charRange.from, charRange.to);
    new import_obsidian3.Notice(`Paragraph moved to "${targetFile.basename}".`);
  }
};
